import { TemplateId } from "@/types/invitation";

export interface TemplateDefinition {
  id: TemplateId;
  name: string;
  nameTelugu: string;
  category: "wedding" | "engagement" | "reception" | "haldi-sangeet" | "heritage";
  description: string;
  badgeText: string;
  bgGradient: string;
  textColor: string;
  accentColor: string;
}

export const TEMPLATE_CATALOG: TemplateDefinition[] = [
  {
    id: "traditional",
    name: "Telugu Heritage",
    nameTelugu: "తెలుగు వారసత్వం",
    category: "wedding",
    description: "Classic ivory paper with deep maroon borders, antique gold accents, and traditional patrika typography.",
    badgeText: "Most Popular",
    bgGradient: "from-[#fdfbf7] to-[#f4eee0]",
    textColor: "#58121a",
    accentColor: "#c59b27",
  },
  {
    id: "royal",
    name: "Royal Temple & Gopuram",
    nameTelugu: "రాజకీయ గోపురం",
    category: "wedding",
    description: "Deep crimson red with royal mandap arch frames, gold foil gopuram motifs, and grand ceremonial feel.",
    badgeText: "Royal Edition",
    bgGradient: "from-[#4a0e17] to-[#2b080c]",
    textColor: "#f5d77f",
    accentColor: "#c59b27",
  },
  {
    id: "floral",
    name: "Minimal Modern Floral",
    nameTelugu: "సరసమైన పూల డిజైన్",
    category: "wedding",
    description: "Warm cream with sage green accents, delicate floral line art, and modern serif typography.",
    badgeText: "Modern Minimal",
    bgGradient: "from-[#f9f6f0] to-[#ece6d9]",
    textColor: "#2d4a3e",
    accentColor: "#8b1220",
  },
  {
    id: "kalamkari",
    name: "Kalamkari Heritage Art",
    nameTelugu: "కళంకారి హస్తకళ",
    category: "heritage",
    description: "Warm rust ochre and earth tones with hand-drawn Kalamkari floral vines and authentic artisan aesthetics.",
    badgeText: "Artisan Heritage",
    bgGradient: "from-[#9c4220] to-[#5e220a]",
    textColor: "#fdfbf7",
    accentColor: "#f7d070",
  },
  {
    id: "banarasi",
    name: "Banarasi Silk Brocade",
    nameTelugu: "బెనారస్ పట్టు శైలి",
    category: "heritage",
    description: "Rich emerald green with intricate gold brocade border motifs, styled after traditional Indian wedding silk sarees.",
    badgeText: "Luxury Silk",
    bgGradient: "from-[#124436] to-[#07241c]",
    textColor: "#f5d77f",
    accentColor: "#ffd700",
  },
  {
    id: "gold-red",
    name: "Gold & Red Traditional",
    nameTelugu: "స్వర్ణ వర్ణ వైభవం",
    category: "wedding",
    description: "Ceremonial deep red backdrop with embossed gold foil frames, traditional line rules, and classic blessings.",
    badgeText: "Auspicious Classic",
    bgGradient: "from-[#7a0c1a] to-[#45050f]",
    textColor: "#ffd700",
    accentColor: "#f5d77f",
  },
  {
    id: "green-gold",
    name: "Green & Gold South Indian",
    nameTelugu: "కాంచీపురం పట్టు శైలి",
    category: "wedding",
    description: "Kanchipuram emerald green with antique brass gold motifs, traditional brass lamps, and ceremonial borders.",
    badgeText: "South Indian Classic",
    bgGradient: "from-[#0d3b2e] to-[#041d16]",
    textColor: "#f0e68c",
    accentColor: "#c59b27",
  },
  {
    id: "vintage",
    name: "Vintage Yellow Patrika",
    nameTelugu: "వింటేజ్ పసుపు పత్రిక",
    category: "heritage",
    description: "Turmeric yellow paper background, vermillion red borders, kalasha icons, and retro vintage Telugu patrika font.",
    badgeText: "Vintage Patrika",
    bgGradient: "from-[#f7d070] to-[#e6b800]",
    textColor: "#7a0c1a",
    accentColor: "#b30000",
  },
  {
    id: "pattachitra",
    name: "Pattachitra Heritage Art",
    nameTelugu: "పట్టచిత్ర సాంప్రదాయం",
    category: "heritage",
    description: "Terracotta red with traditional Indian folk art borders, peacock motifs, and sacred wedding symbols.",
    badgeText: "Folk Art Heritage",
    bgGradient: "from-[#8b2500] to-[#4d1400]",
    textColor: "#ffecb3",
    accentColor: "#ffab00",
  },
  {
    id: "luxury",
    name: "Modern Luxury Dark",
    nameTelugu: "ఆధునిక రాజస రాత్రి",
    category: "wedding",
    description: "Obsidian black backdrop with shimmering gold foil text, minimalist luxury serif typography, and premium vibe.",
    badgeText: "Premium Luxury",
    bgGradient: "from-[#0f172a] to-[#020617]",
    textColor: "#fef08a",
    accentColor: "#eab308",
  },
  {
    id: "pastel",
    name: "Pastel Floral Romance",
    nameTelugu: "ప్రశాంత గులాబీ వసంతం",
    category: "wedding",
    description: "Soft blush pink with rose gold leaf borders, subtle botanical watercolors, and romantic typography.",
    badgeText: "Romantic Pastel",
    bgGradient: "from-[#fdf2f4] to-[#f5d6dc]",
    textColor: "#881337",
    accentColor: "#e11d48",
  },
  {
    id: "contemporary",
    name: "Contemporary Photo-First",
    nameTelugu: "ఫోటో ఆల్బమ్ వైభవం",
    category: "wedding",
    description: "Editorial full-screen photo canvas design with glassmorphic cards, large portrait focus, and clean layout.",
    badgeText: "Photo Focused",
    bgGradient: "from-[#1c1917] to-[#0c0a09]",
    textColor: "#f5f5f4",
    accentColor: "#d97706",
  },
  {
    id: "cinematic",
    name: "Cinematic Midnight",
    nameTelugu: "సినిమాటిక్ నక్షత్ర రాత్రి",
    category: "wedding",
    description: "Midnight navy blue backdrop with shimmering gold star dust, dramatic cinematic hero fonts, and luxury feel.",
    badgeText: "Cinematic Edition",
    bgGradient: "from-[#0b1329] to-[#030712]",
    textColor: "#fef08a",
    accentColor: "#fbbf24",
  },
  {
    id: "family",
    name: "Family Blessings",
    nameTelugu: "కుటుంబ ఆశీర్వచన పత్రిక",
    category: "wedding",
    description: "Warm parchment paper layout with prominent family elders section, auspicious kalasha icons, and clean structure.",
    badgeText: "Family Classic",
    bgGradient: "from-[#fffdfa] to-[#f5ebd7]",
    textColor: "#4a2e1b",
    accentColor: "#8b6508",
  },
  {
    id: "festive",
    name: "Festive Celebration",
    nameTelugu: "సంబరాల పండుగ శైలి",
    category: "haldi-sangeet",
    description: "Vibrant marigold orange with mango leaf toran borders, festive dholak graphics, and joyful wedding celebration vibe.",
    badgeText: "Festive Joy",
    bgGradient: "from-[#e65100] to-[#992200]",
    textColor: "#fff8e1",
    accentColor: "#ffb300",
  },
  {
    id: "engagement",
    name: "Nischitardham Special",
    nameTelugu: "శుభ నిశ్చితార్థం",
    category: "engagement",
    description: "Elegant lavender blush theme with diamond ring emblem motifs, specialized for Telugu Nischitardham ceremonies.",
    badgeText: "Nischitardham Special",
    bgGradient: "from-[#5b2c6f] to-[#2c133a]",
    textColor: "#f4ecf7",
    accentColor: "#af7ac5",
  },
  {
    id: "reception",
    name: "Grand Reception Night",
    nameTelugu: "అట్టహాస రిసెప్షన్",
    category: "reception",
    description: "Royal velvet purple backdrop with gold champagne sparkle accents, black-tie evening aesthetic, and celebration card.",
    badgeText: "Reception Special",
    bgGradient: "from-[#3b125d] to-[#1a052c]",
    textColor: "#fef08a",
    accentColor: "#d4af37",
  },
  {
    id: "haldi",
    name: "Haldi Ceremony Special",
    nameTelugu: "హల్దీ రంగుల పండుగ",
    category: "haldi-sangeet",
    description: "Bright haldi turmeric yellow with marigold flower garland frames, sunny auspicious vibe, and playful floral art.",
    badgeText: "Haldi Special",
    bgGradient: "from-[#fbc02d] to-[#f57f17]",
    textColor: "#3e2723",
    accentColor: "#d84315",
  },
  {
    id: "sangeet",
    name: "Sangeet & Mehendi Beats",
    nameTelugu: "సంగీత్ & మెహందీ సందడి",
    category: "haldi-sangeet",
    description: "Peacock teal and rich violet theme with dholak, tabla, and intricate henna mehendi art motifs for pre-wedding parties.",
    badgeText: "Sangeet & Mehendi",
    bgGradient: "from-[#00695c] to-[#4a148c]",
    textColor: "#e0f2f1",
    accentColor: "#80cbd4",
  },
  {
    id: "sacred-vivaha",
    name: "Sacred Vivaha Muhurtham",
    nameTelugu: "పవిత్ర వివాహ హోమం",
    category: "wedding",
    description: "Vedic sacred fire crimson red with saptapadi icons, mangalya dharanam gold emblems, and sacred Telugu mantras.",
    badgeText: "Vedic Sacred",
    bgGradient: "from-[#b71c1c] to-[#5f0909]",
    textColor: "#fff8e1",
    accentColor: "#ffd700",
  },
];
